/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:590f3423-9cc9-4d36-b0ca-20b8b4be6d67",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3t6nczsqT",
    "aws_user_pools_web_client_id": "1pp74ra8t8iapfemf64f62ltp0",
    "oauth": {}
};


export default awsmobile;
